/**
 * Serves landing.html at the root route (/).
 *
 * Reads the root-level landing.html directly so edits to that file
 * are immediately reflected — no rebuild needed in dev.
 *
 * Path substitution converts the static-file paths in landing.html
 * to the /public-relative paths that Next.js serves:
 *   app/public/  →  /
 *   app/resources/  →  /fonts/
 */

import fs from 'fs'
import path from 'path'

export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'

function fixPaths(html: string): string {
  return html
    .replace(/app\/public\//g, '/')
    .replace(/app\/resources\//g, '/fonts/')
}

export async function GET() {
  // Local dev: root landing.html lives one level up from the app/ folder.
  // Vercel: root landing.html is also available since the full repo is deployed.
  // Fallback: public/landing.html (generated by the prebuild script).
  const candidates = [
    path.join(process.cwd(), '..', 'landing.html'),
    path.join(process.cwd(), 'public', 'landing.html'),
  ]

  let html: string | null = null
  for (const p of candidates) {
    if (fs.existsSync(p)) {
      html = fixPaths(fs.readFileSync(p, 'utf-8'))
      break
    }
  }

  if (!html) {
    return new Response('<h1>Landing page not found</h1>', {
      status: 404,
      headers: { 'Content-Type': 'text/html' },
    })
  }

  return new Response(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-store',
    },
  })
}
