/**
 * Serves landing.html at the root route (/).
 *
 * Reads the root-level landing.html directly so edits to that file
 * are immediately reflected — no rebuild needed in dev.
 *
 * Path substitution converts the static-file paths in landing.html
 * to the /public-relative paths that Next.js serves:
 *   app/public/  →  /
 *   app/resources/  →  /fonts/
 */

import fs from 'fs'
import path from 'path'
import { cookies } from 'next/headers'

export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'

const COOKIE_NAME = 'interplay_access'
const COOKIE_VALUE = 'granted'

function fixPaths(html: string): string {
  return html
    .replace(/app\/public\//g, '/')
    .replace(/app\/resources\//g, '/fonts/')
}

export async function GET() {
  // Password gate — redirect to /unlock if cookie not present
  const jar = await cookies()
  if (jar.get(COOKIE_NAME)?.value !== COOKIE_VALUE) {
    return new Response(null, {
      status: 302,
      headers: { Location: '/unlock' },
    })
  }


  // Local dev: root landing.html lives one level up from the app/ folder.
  // Vercel: root landing.html is also available since the full repo is deployed.
  // Fallback: public/landing.html (generated by the prebuild script).
  const candidates = [
    path.join(process.cwd(), '..', 'landing.html'),
    path.join(process.cwd(), 'public', 'landing.html'),
  ]

  let html: string | null = null
  for (const p of candidates) {
    if (fs.existsSync(p)) {
      html = fixPaths(fs.readFileSync(p, 'utf-8'))
      break
    }
  }

  if (!html) {
    return new Response('<h1>Landing page not found</h1>', {
      status: 404,
      headers: { 'Content-Type': 'text/html' },
    })
  }

  // Expire the cookie immediately — forces password entry on every visit
  return new Response(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-store',
      'Set-Cookie': `${COOKIE_NAME}=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax`,
    },
  })
}
